### ISSUE TITLE
Signature for stubbing objects with two different arguments set

### ISSUE THREAD

**Issue by Subomi** [rspec/rspec-mocks#1264] opened 2019-02-08 07:10 UTC
### Environment
* Ruby version: 2.4
* rspec-mocks version: 3.7.0

### Expected behavior
`allow(Object).to receive(:method).with(arg).and_return(one)`
`allow(Object).to receive(:method).with(arg_two).and_return(two)`

I expect the two allow statements above to be different but rspec doesn't treat them differently?

What will be the best approach to stub this object?

**Comment by Darhazer** [comment] 2019-02-08 10:46
This works. Maybe you have a larger example in which something is not as expected.
Minimal reproducible example to prove it works:

```
class A
  def method;end
end

RSpec.describe A do
  before do
    allow(A).to receive(:method).with('first').and_return(1)
    allow(A).to receive(:method).with('two').and_return(2)
  end

  specify do
    expect(A.method('first')).to eq 1
    expect(A.method('two')).to eq 2
  end
end
```

**Comment by JonRowe** [comment] 2019-02-08 15:56
@Subomi Can you provide more information on what you expect to happen and isn't?

**Comment by benoittgt** [comment] 2019-02-11 10:16
Feel free to use https://github.com/rspec/rspec-mocks/blob/master/REPORT_TEMPLATE.md

**Comment by Subomi** [comment] 2019-02-11 15:34
I expect the two expectations should be treated differently and respond accordingly. 

Sorry for the late response.

**Comment by JonRowe** [comment] 2019-02-11 15:35
@Subomi They are, they do, see our examples, you're going to have to provide more information on whats going wrong for you.

**Comment by benoittgt** [comment] 2019-04-04 17:18
I am closing the issue because we don't have enough information. @Subomi we can reopen it if you provide a reproduction script.

Thanks

**Closed by benoittgt** 2019-04-04 17:18 UTC
