### ISSUE TITLE
have_received(...).with(...) exception on 3.2

### ISSUE THREAD

**Issue by elado** [rspec/rspec-mocks#887] opened 2015-02-05 03:54 UTC
I have a simple example, something like:

```ruby
it "should share a post when created" do
  post = create(:post)
  expect(SharingService).to have_received(:share).with(hash_including(id: post.id))
end
```

For this example, let's say that `SharingService.share` is called on `after_create` with `{id: post.id}` and maybe other keys/values, and I want to validate it.

With `3.2` and #868 - I get this error:

```
`have_received(...).with(...)` cannot be used when received message args have later been mutated. You can use a normal message expectation (`expect(...).to receive(...).with(...)`) instead.
```

I can't use `receive().with()` because I don't have the ID of the post, and the operation is done inside the creation stage.

Worked perfectly with `3.1`. I think the issue is only with `hash_including` or other matchers.

Is there another way to do it, or is it a bug?

**Comment by elado** [comment] 2015-02-05 04:01
@JonRowe closed?

**Comment by JonRowe** [comment] 2015-02-05 04:02
This warning is new in 3.2, its being triggered because the hash is mutated

**Comment by myronmarston** [comment] 2015-02-05 04:05
Not sure why he closed it so quick, but for the story behind this see #865 and the fix we applied in #868. `have_received` is not able to work properly when the arguments passed on a spied method call are mutated before `have_received` is used, so we now explicitly tell you rather than having buggy behavior.

Can you change your logic so that it no longer mutates the hash after passing it to `SharingService.share`?  (That's generally a good idea, anyway).

Alternately you could do something like:

``` ruby
it "should share a post when created" do
  shared_id = nil
  expect(SharingService).to receive(:share) { |id:, **rest| shared_id = id }
  post = create(:post)
  expect(shared_id).to eq(post.id)
end
```

**Comment by JonRowe** [comment] 2015-02-05 04:06
I closed it because I initially thought this was due to the hash being mutated (was half way through writing a reply then got distracted, sorry) but I actually think this could be a legitimate bug caused by using the matcher?

**Comment by myronmarston** [comment] 2015-02-05 04:08
> but I actually think this could be a legitimate bug caused by using the matcher?

If you look at the implementation in #868, you'll see that the argument to `with` doesn't even come into play when deciding whether or not to raise this error -- it's based entirely on the value of `arg_list.hash` when the message was received vs when `have_received` is used.  So either the hash was indeed mutated or there's a buggy implementation of `#hash` on your hash object (e.g. due to a monkey patch by something).

**Comment by myronmarston** [comment] 2015-02-05 04:11
BTW, it may not be the hash itself that's been mutated -- it could be one of the keys or values in the hash, or an object referred to by one of the keys or values, that's been mutated.  I believe `Hash#hash` is a function of `#hash` on all its keys and values so if any of them are mutated the hash indicates that it has mutated.

**Comment by JonRowe** [comment] 2015-02-05 04:12
Ah was just about to look into it, you're correct of course :)

**Comment by elado** [comment] 2015-02-05 04:13
I'm not sure I understand what hash was mutated. Can you please explain?

**Comment by JonRowe** [comment] 2015-02-05 04:14
The argument to `#share`

**Comment by JonRowe** [comment] 2015-02-05 04:14
(sorry wrong button that time)

**Comment by myronmarston** [comment] 2015-02-05 04:15
> The argument to #share

Right...it could be the implementation of `#share` itself that mutates the provided hash.  Or it could be that the caller retains a reference to the hash passed to `#share` and mutates it...or something `#share` delegates to, etc.

**Closed by JonRowe** 2015-02-05 04:14 UTC

**Comment by elado** [comment] 2015-02-05 04:20
So if I have:

```ruby
class Post
  after_create :share
  def share
    SharingService.share id: self.id, message: self.title
  end
end

class SharingService
  def self.share(id:, message:)
     ...
  end
end
```

(Just an example, not the real code)

What's mutated?

Or does it happen only if SharingService looks like:

```ruby
class SharingService
  def self.share(options)
     id = options.delete(:id) # now I'm mutated!
     # ...
  end
end
```

?

If the latter is the case I'll probably have to change the spec logic as you suggested.

**Comment by myronmarston** [comment] 2015-02-05 04:22
The former doesn't mutate anything, as far as the included code goes. (The logic in `...` could mutate `message` or `id` later, though).

The `options.delete(:id)` does mutate `options` -- and it means that the mutation is visible to the caller, too, which you generally don't want...it tends to lead to surprising bugs and be hard to reason about.  You can always add an `options = options.dup` at the first line, or stub `SharingService.share` in your spec so that logic isn't run.

**Comment by elado** [comment] 2015-02-05 19:29
Got it, thanks. It was indeed mutated somewhere.

Here's another issue:

```ruby
allow(UserPasswordService).to receive(:set_password).and_call_original
user = UserService.create! email: "e@mail.com", password: "abcdefg"
expect(UserPasswordService).to have_received(:set_password).with(user, "abcdefg")
```

The `UserService` mutates the `user` by setting its attributes, and `UserPasswordService` sets more attributes.
If I don't call original `user` won't have password fields and SQL will fail.

I couldn't combine `and_call_original` with the block to catch the arguments as suggested earlier.

Suggestions?

**Comment by myronmarston** [comment] 2015-02-05 19:34
> I couldn't combine and_call_original with the block to catch the arguments as suggested earlier.

You can use `and_wrap_original`:

``` ruby
updated_user = nil
expect(UserPasswordService).to receive(:set_password).and_wrap_original do |original_method, user, password, &block|
  updated_user = user
  original_method.call(user, password, &block)
end

user = UserService.create! email: "e@mail.com", password: "abcdefg"
expect(updated_user).to eq(user)
```

All that said, IMO it's a code smell to use partial doubles (e.g. to use mocking on a real object rather than a test double).  The "mock roles not objects" principle is about using a test double to fill a role as an alternate implementation of some protocol.  Given that you're using real objects rather than test doubles, I would recommend doing state-based verification instead.
