### ISSUE TITLE
spies don't tolerate changing arguments

### ISSUE THREAD

**Issue by x-yuri** [rspec/rspec-mocks#865] opened 2015-01-15 04:33 UTC
```ruby
describe 'rspec-mocks' do
  it 'passes with a double' do
    d = double('d').as_null_object
    expect(d).to receive(:m).with(hash_including('offset' => 1))
    args = {}
    args['offset'] = 1
    d.m args
    args['offset'] = 2
    d.m args
  end

  it 'passes with a spy' do
    d = spy('d')
    args = {}
    args['offset'] = 1
    d.m args
    args['offset'] = 2   # it passes if you comment
    d.m args             # out these two lines
    expect(d).to have_received(:m).with(hash_including('offset' => 1))
  end
end
```

**Comment by myronmarston** [comment] 2015-01-15 08:31
Thanks for reporting this with such a clear repro case, @x-yuri!  I started digging into this and I've gotten to the point of understanding what's causing the problem, but I'm not yet sure how to fix it.  What I have so far is in a branch:

https://github.com/rspec/rspec-mocks/compare/master...address-issue-865

The problem is our `have_received` implementation...here's how it works:

* All test doubles (and stubbed methods on partial doubles) record their received messages and received arguments as they receive them.
* `have_received` supports the same fluent interface as normal message expectations by internally building a message expectation and delegating the chained method calls to that, so that `expect(x).to have_received(:foo).with(arg).exactly(3).times` generates a message expectation that's configured to expect `:foo` with `arg` exactly 3 times.
* `have_received` then replays any recorded messages onto the generated message expectation.
* It then verifies the message expectation to see if it has been satisfied.

This record/replay mechanism is prone to problems like the one @x-yuri has reported when dealing with mutable values.  When recording received messages, it holds on to references to all passed arguments so that it can replay them later...but if those passed arguments are mutated between recording and replaying, then it replays it with the mutated value, so an expectation that the message was received with the original value will fail.

Fixing this is not going to be simple. We can try to make the recording mechanism hold on to a `clone` (or `dup`) of the provided args, so that the values it has are unaffected by later mutations.  However, given how easy it is to create nested mutable data structures, duping or cloning an argument only protects us from mutation at that level.  If anything within the data structure is mutated, we're not protected.  So we'd have to do a deep-dup or deep-clone, but that's uggggh.  In the past, I've used `Marshal.load(Marshal.dump object)` for that but that's not going to perform well and some things (such as `Proc` objects, sockets, etc) cannot be dumped by `Marshal`.  I think that any solution here is going to be an approximate, heuristic solution that prevents the bug for certain cases while leaving it unsolved for others while generally leaving the root problem in tact.

I was originally thinking that refactoring our spy implementation away from a replay mechanism would also solve this but now I'm realizing that it wouldn't -- even if `have_received` just compared to recorded messages (w/o replaying them), the recorded messages would still have references to mutable values that, if changed before executing a `have_received` expectation, would fail in the same way.

So I'm not really sure how to go about fixing this.  Any ideas, @rspec/rspec?  @jferris, as author of the original rspec-mocks spy implementation, perhaps you have some bright ideas?

**Comment by jferris** [comment] 2015-01-15 16:42
Ah, the old "pass some arguments by reference and then mutate them" maneuver. A classic!

A couple suggestions:

* Call `freeze` on all the arguments. Doesn't catch everything and the errors could be annoying, but it will catch the more common cases and places the performance burden on those who engage in mutation.
* Check the `hash` of all arguments before recording and replay. Even for deeply nested structures, the `hash` should be a good indicator of whether or not something has changed. I think it's also reasonably fast, and you can control the error messages.

**Comment by myronmarston** [comment] 2015-01-15 17:03
Thanks, @jferris!  I hadn't considered these.  I take it that you're suggesting that we don't actually make this work but instead provide a clear error to the user so they know they can't use `have_received` with mutated arguments?

> Call `freeze` on all the arguments. Doesn't catch everything and the errors could be annoying, but it will catch the more common cases and places the performance burden on those who engage in mutation.

I think this would be a surprising side effect for end users (and would almost certainly be a breaking change).  Consider that we record _every_ invocation of _every_ method to a test double or an stub/expectation on a partial double...and you've got a ton of situations where the user isn't going to use `have_received`.  Having all arguments frozen would be surprising for a lot of users and would almost certainly be a breaking change.

> Check the `hash` of all arguments before recording and replay. Even for deeply nested structures, the `hash` should be a good indicator of whether or not something has changed. I think it's also reasonably fast, and you can control the error messages.

I think I like this idea a lot -- there aren't the side effects that `freeze` brings, and it allows us to provide an error message in the specific situation when `have_received` causes replayed messages with mutated args.  Unless someone comes up with a better idea for how to simply and correctly make this work, I think I'll take a stab at this soon.

Thanks again!

**Comment by jferris** [comment] 2015-01-15 18:15
Yeah, `freeze` was the simplest thing I could think of, but I'm not sure I've ever used it without regretting it later.

Happy to help! I hope the `hash` approach works out.

**Comment by myronmarston** [comment] 2015-01-16 06:55
The `hash` approach did indeed work out pretty well -- you can see my implementation in #868 if you're curious.

@x-yuri -- sorry that our fix for this doesn't actually make it work but it should at least give you a clear error once #868 is merged.

**Comment by x-yuri** [comment] 2015-01-16 20:17
No problem, I reported mainly so that you knew about the issue. And I seem to agree that there's no sane way to solve the problem. I might have even gone so far as to say that just having a note in `README` will suffice.

**Comment by myronmarston** [comment] 2015-01-16 20:22
I'm glad you reported the issue -- I didn't realize this problem before, and giving users clear errors when they do something unsupported is really important.  A note in the README might help some users but others wouldn't see it and in other situations you might not even be aware the args are being mutated (such as when you pass those args to another bit of code you didn't write and it happens to mutate them).

**Closed** 2015-01-18 22:29 UTC
