### ISSUE TITLE
Why is the negated have_received matcher not supported?

### ISSUE THREAD

**Issue by randycoulman** [rspec/rspec-mocks#968] opened 2015-06-07 02:26 UTC
According to the README, it is allowable to have a spy expectation like:

```ruby
expect(invitation).to_not have_received(:accept).with(mailer)
```
However, this is explicitly disallowed by the code in `targets.rb`.  Is there a reason that this is not supported?  The matcher itself seems to support it just fine.

As I've investigated further, this syntax **is** allowed when using RSpec, but is disallowed when using rspec-mocks within Minitest.

I believe that, if the problem in `targets.rb` is fixed, a new error will appear that is analogous to #967 because the `HaveReceived` matcher doesn't implement `setup_negative_expectation`.

**Comment by myronmarston** [comment] 2015-06-07 06:23
Negated `have_received` is supported.  We have many specs that confirm that:

https://github.com/rspec/rspec-mocks/blob/0dd16e3a79604124e416d7bd934df138515d9afc/spec/rspec/mocks/matchers/have_received_spec.rb#L515-L560

> However, this is explicitly disallowed by the code in `targets.rb`.

In targets, negation is only disallowed for `allow`; e.g. `allow(x).not_to` is not supported.

> As I've investigated further, this syntax is allowed when using RSpec, but is disallowed when using rspec-mocks within Minitest.

As explained in #967, the problem is that `have_received` only works when you are also using rspec-expectations.

Closing since I think #967 more accurately reflects the problem you're having.

**Closed by myronmarston** 2015-06-07 06:23 UTC

**Comment by randycoulman** [comment] 2015-06-07 06:34
I think that doing what you suggest in #967 will fix my problem, I agree.

But in the case statement in `targets.rb`:

https://github.com/rspec/rspec-mocks/blob/0dd16e3a79604124e416d7bd934df138515d9afc/lib/rspec/mocks/targets.rb#L21-L28

the `HaveReceived` matcher falls through to the else clause and gets reported as an unsupported matcher.

**Comment by myronmarston** [comment] 2015-06-07 06:45
> I think that doing what you suggest in #967 will fix my problem, I agree.
> 
> But in the case statement in targets.rb:
> 
> https://github.com/rspec/rspec-mocks/blob/0dd16e3a79604124e416d7bd934df138515d9afc/lib/rspec/mocks/targets.rb#L21-L28
> 
> the HaveReceived matcher falls through to the else clause and gets reported as an unsupported matcher.

Thanks, now I see what you are referring to!

It's intentional that `HaveReceived` falls through as it's a "real" matcher that can only work when passed to rspec-expectations' implementation of `expect` (which is always used if both rspec-mocks and rspec-expectations are loaded).  The other classes listed in that code are not "real" matchers; they implement the matcher protocol simply to provide for syntax consistency.  rspec-mocks' more limited implementation of `expect` is able to support them just fine.

Again, I apologize for the poor documentation and experience around this.
