### ISSUE TITLE
Expecting kwargs does not work in Ruby 3.2. 

### ISSUE THREAD

**Issue by wuarmin** [rspec/rspec-mocks#1523] opened 2023-02-07 14:45 UTC
### Your environment
* Ruby version: 3.2
* rspec-mocks version: 3.12

### Steps to reproduce
```ruby
# set up double
repo_double = instance_double(MyRepo)
expect(repo_double).to receive(:filter).with(first_name: "Michael", last_name: "Knight").and_return([]) 

# call filter of double in implementation
filter = { first_name: "Michael", last_name: "Knight" }
repo.filter(**filter)
```
fails with
```txt
#<InstanceDouble(Repositories::MyRepo) (anonymous)> received :filter with unexpected arguments
         expected: ({:first_name=>"Michael", :last_name=>"Knight"}) (keyword arguments)
              got: ({:first_name=>"Michael", :last_name=>"Knight"}) (options hash)
```

### Expected behavior
the spec should not fail. This code worked in Ruby 3.1.2

### Actual behavior
the spec fails

Thanks

**Comment by JonRowe** [comment] 2023-02-07 15:53
Whats the implementation of filter? As you can see from other issues we're aware of some differences in Ruby 3.2 so this is probably a duplicate.

**Comment by pirj** [comment] 2023-02-07 17:03
In general, there should be no difference in 3.2?
```ruby
a = {a: 1, b: 2}

def x(**opt)
  puts opt.inspect
end
def y(a:, b:)
  puts a + b
end
def x(opt)
  puts opt.inspect
end

x(**a) # => {:a=>1, :b=>2}
y(**a) # => 3
z(**a) # => {:a=>1, :b=>2}
```

**Comment by JonRowe** [comment] 2023-02-07 20:41
It makes a difference because:

**Comment by JonRowe** [comment] 2023-02-07 20:46
@pirj, in the case of `def x(opt)` RSpecs output above would be correct, it doesn't take keyword arguments, and in general using `**kwargs` to an argument as a hash is a duplicate of #1492 and there is something that changed there, but honestly people shouldn't be de-splating keyword arguments to hashes

**Comment by wuarmin** [comment] 2023-02-09 07:23
@JonRowe here's the implementation of `filter`
```ruby
def filtered(**filter)
  get("customers", filter)
end

private

def get(path, params = {})
  conn.get(path, params)
end
```

**Comment by gregg-platogo** [comment] 2023-06-06 10:08
That's what we came up with to fix this issue https://github.com/platogo/rspec-mocks/commit/6cdc4867952c4c5f8f47fdfea112ca785a9e3cd3

**Comment by pirj** [comment] 2023-06-06 20:50
This is interesting, @gregg-platogo !
Wondering if it would work like we do e.g. [here](https://github.com/rspec/rspec-mocks/blob/0d22620149a66d38ed03f60e96045721d71ce134/lib/rspec/mocks/message_expectation.rb#L145):
```ruby
        @original_implementation_callable ||= original_method ||
          Proc.new do |*args, &block|
            @object.__send__(:method_missing, @method_name, *args, &block)
          end.tap do |proc|
            proc.ruby2_keywords if proc.respond_to?(:ruby2_keywords)
          end
```
Would you be so kind to check if this would work for your cases?

**Comment by ngouy** [comment] 2023-06-13 03:49
Digging internet late at night, I think the issue is here no ?

![image](https://github.com/rspec/rspec-mocks/assets/12391171/5a2fd38a-9f97-4e26-b8ae-cc27e905f871)

We should capture args and kwargs, I might be wrong of course

**Comment by ngouy** [comment] 2023-06-13 03:52
yea. When I monkey patch to 
![image](https://github.com/rspec/rspec-mocks/assets/12391171/7cff1571-d04c-41cf-b6cd-433283093869)

My pre-ruby 3 working, now not working test is finally green again

**Comment by ngouy** [comment] 2023-06-13 03:53
I don't have time nor faith to write the spec, hence make a PR. But I think that's it

**Comment by jonfreeland** [comment] 2023-07-30 18:07
This is working for me as well, code for convenience:

```ruby
module RSpec
  module Mocks
    class MessageExpectation
      def and_call_original
        block = lambda do |original, *args, **kwargs, &b|
          original.call(*args, **kwargs, &b)
        end
        block = block.ruby2_keywords if block.respond_to?(:ruby2_keywords)

        wrap_original(__method__, &block)
      end
    end
  end
end
```

It still results in a warning:
`Skipping set of ruby2_keywords flag for proc (proc accepts keywords or proc does not accept argument splat)`

But tests are green.

**Comment by igor-drozdov** [comment] 2023-07-31 09:39
@jonfreeland I wonder if the issue is fixed in 3.12.6 by this PR: https://github.com/rspec/rspec-mocks/pull/1552

@gregg-platogo 3.12.6 now contains the fix that is very similar to [yours](https://github.com/rspec/rspec-mocks/issues/1523#issuecomment-1578347022): https://github.com/rspec/rspec-mocks/pull/1552. Could you please verify that it works for you?

**Comment by gregg-platogo** [comment] 2023-07-31 09:43
Yes, we did update to 3.12.6 last week and it does work like a charm ❤️ Thank you guys!

**Comment by igor-drozdov** [comment] 2023-07-31 09:45
@JonRowe I wonder if this issue can be closed now, WDYT?

**Comment by DylanEtris** [comment] 2024-01-14 15:14
I noticed that this issue hasn't had any updates in a while and the issue has been resolved, can it be closed?

**Comment by pirj** [comment] 2024-01-14 18:57
Seems fixed. Thanks everyone involved.

**Closed by pirj** 2024-01-14 18:57 UTC
Labels: needs-reproduction
