### ISSUE TITLE
expect(Object).to have_received(:method).with(param) fails if parameter is later modified

### ISSUE THREAD

**Issue by williamhakim10** [rspec/rspec-mocks#1419] opened 2021-03-19 00:18 UTC
### Subject of the issue

In our tests, we may sometimes want to mock an object and assert that the object has received a certain method with a certain set of arguments. However, if one of those arguments is a reference (e.g. a hash) and the argument is later modified (e.g., a new key is added to the hash), the expectation fails.

### Your environment
* Ruby version: 2.6.6.
* rspec-mocks version: 3.9.1

### Steps to reproduce

```
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  gem "rspec", "3.9.1" # Activate the gem and version you are reporting the issue against.
end

puts "Ruby version is: #{RUBY_VERSION}"
require 'rspec/autorun'

class MyObj < Object
  def my_method(*args)
  end
end

RSpec.describe 'additions' do
  it 'returns 2' do
    allow(MyObj).to receive(:my_method)

    map = { a: 1 }
    MyObj.my_method(map)
    map[:b] = 2 # This is obviously weird inside a test, but could very easily happen in actual code under test

    expect(MyObj).to have_received(:my_method).with({ a: 1 })
  end
end
```

### Expected behavior

The expectation should pass; perhaps rspec should clone the objects that the mocked method receives rather than simply using the reference.

### Actual behavior

The expectation fails.

We're happy to help fixing this issue, however we're a little confused as to the exact structure of expectations in rspec-mocks. If this is indeed an issue the team is interested in fixing, with a little guidance perhaps we'd be able to provide a PR.

**Comment by benoittgt** [comment] 2021-03-19 06:17
Hello @williamhakim10 

What you could do is. Set the spy, then expect when it has been called. For example:

```ruby
RSpec.describe 'additions' do
  it 'returns 2' do
    expect(MyObj).to receive(:my_method).with({ a: 1 })

    map = { a: 1 }
    MyObj.my_method(map)
    map[:b] = 2 # This is obviously weird inside a test, but could very easily happen in actual code under test
  end
end
```

**Comment by benoittgt** [comment] 2021-03-19 06:19
I think this is a duplicate of https://github.com/rspec/rspec-mocks/issues/1251

**Closed** 2021-03-19 06:21 UTC
