### ISSUE TITLE
Allow multiple receive counts for an expected message

### ISSUE THREAD

**Issue by AlbertoTejada** [rspec/rspec-mocks#1443] opened 2021-11-12 15:55 UTC
### Allow multiple receive counts matchers for an expected message
Only the last counter matcher in a expectation is considerer, the rest are ignored.

### Your environment
* Ruby version: 3.6.6
* rspec-mocks version: 3.10.2

### Steps to reproduce
Define an expectation with a counter range: 
```
 it 'receives message between 5 and 6 times ' do
   expect(receiver).to receive(:message).at_least(5).at_most(6).times
   method_call
 end
```

### Expected behavior
Expect the case to fail if `message` is received less than 5 times **OR** more than 6 times

### Actual behavior
The test case fails if `message` is received more than 6 times, but it passes when `message` is received less than 5 times

**Comment by pirj** [comment] 2021-11-12 16:30
Thanks for reporting.
This is a duplicate of #1426 if I'm not mistaken.
There are several problems with counts if you check comments, and a suggestion how to improve that.
Pull requests are welcome!

**Closed by pirj** 2021-11-12 16:30 UTC
